services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '19090:9090'

  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - '13000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

  backend:
    build: ./backend
    ports:
      - '8080:8080'

volumes:
  grafana-data:
